services:
  - type: web
    name: my-portfolio-web
    env: docker
    branch: main
    plan: free
    dockerfilePath: Dockerfile
    buildCommand: "npm ci && npm run build"
    startCommand: "sh scripts/start-production.sh"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: '1'
      - key: DATABASE_URL
        value: file:/app/data/portfolio.db
